# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'SW-sdk-NetStandard.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'SW-sdk-NetStandard.sln'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'test/sdk-test/Resources'
    Contents: '**'
    TargetFolder: 'test/sdk-test/bin/Release/netcoreapp2.2'
    OverWrite: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'test/sdk-test/sdk-test.csproj'
    publishTestResults: false
    workingDirectory: 'test/sdk-test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/sw-sdk/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'versionsuffix'
- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: 'NugetORG'
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NugetORG'